import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ISO 3166-1 alpha-2 country codes with names and flag emojis
const countries = [
  { code: 'AF', name: 'Afghanistan', flagEmoji: '🇦🇫' },
  { code: 'AX', name: 'Åland Islands', flagEmoji: '🇦🇽' },
  { code: 'AL', name: 'Albania', flagEmoji: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', flagEmoji: '🇩🇿' },
  { code: 'AS', name: 'American Samoa', flagEmoji: '🇦🇸' },
  { code: 'AD', name: 'Andorra', flagEmoji: '🇦🇩' },
  { code: 'AO', name: 'Angola', flagEmoji: '🇦🇴' },
  { code: 'AI', name: 'Anguilla', flagEmoji: '🇦🇮' },
  { code: 'AQ', name: 'Antarctica', flagEmoji: '🇦🇶' },
  { code: 'AG', name: 'Antigua and Barbuda', flagEmoji: '🇦🇬' },
  { code: 'AR', name: 'Argentina', flagEmoji: '🇦🇷' },
  { code: 'AM', name: 'Armenia', flagEmoji: '🇦🇲' },
  { code: 'AW', name: 'Aruba', flagEmoji: '🇦🇼' },
  { code: 'AU', name: 'Australia', flagEmoji: '🇦🇺' },
  { code: 'AT', name: 'Austria', flagEmoji: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaijan', flagEmoji: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', flagEmoji: '🇧🇸' },
  { code: 'BH', name: 'Bahrain', flagEmoji: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', flagEmoji: '🇧🇩' },
  { code: 'BB', name: 'Barbados', flagEmoji: '🇧🇧' },
  { code: 'BY', name: 'Belarus', flagEmoji: '🇧🇾' },
  { code: 'BE', name: 'Belgium', flagEmoji: '🇧🇪' },
  { code: 'BZ', name: 'Belize', flagEmoji: '🇧🇿' },
  { code: 'BJ', name: 'Benin', flagEmoji: '🇧🇯' },
  { code: 'BM', name: 'Bermuda', flagEmoji: '🇧🇲' },
  { code: 'BT', name: 'Bhutan', flagEmoji: '🇧🇹' },
  { code: 'BO', name: 'Bolivia', flagEmoji: '🇧🇴' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flagEmoji: '🇧🇦' },
  { code: 'BW', name: 'Botswana', flagEmoji: '🇧🇼' },
  { code: 'BV', name: 'Bouvet Island', flagEmoji: '🇧🇻' },
  { code: 'BR', name: 'Brazil', flagEmoji: '🇧🇷' },
  { code: 'IO', name: 'British Indian Ocean Territory', flagEmoji: '🇮🇴' },
  { code: 'BN', name: 'Brunei Darussalam', flagEmoji: '🇧🇳' },
  { code: 'BG', name: 'Bulgaria', flagEmoji: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', flagEmoji: '🇧🇫' },
  { code: 'BI', name: 'Burundi', flagEmoji: '🇧🇮' },
  { code: 'CV', name: 'Cabo Verde', flagEmoji: '🇨🇻' },
  { code: 'KH', name: 'Cambodia', flagEmoji: '🇰🇭' },
  { code: 'CM', name: 'Cameroon', flagEmoji: '🇨🇲' },
  { code: 'CA', name: 'Canada', flagEmoji: '🇨🇦' },
  { code: 'KY', name: 'Cayman Islands', flagEmoji: '🇰🇾' },
  { code: 'CF', name: 'Central African Republic', flagEmoji: '🇨🇫' },
  { code: 'TD', name: 'Chad', flagEmoji: '🇹🇩' },
  { code: 'CL', name: 'Chile', flagEmoji: '🇨🇱' },
  { code: 'CN', name: 'China', flagEmoji: '🇨🇳' },
  { code: 'CX', name: 'Christmas Island', flagEmoji: '🇨🇽' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', flagEmoji: '🇨🇨' },
  { code: 'CO', name: 'Colombia', flagEmoji: '🇨🇴' },
  { code: 'KM', name: 'Comoros', flagEmoji: '🇰🇲' },
  { code: 'CG', name: 'Congo', flagEmoji: '🇨🇬' },
  { code: 'CD', name: 'Congo, Democratic Republic of the', flagEmoji: '🇨🇩' },
  { code: 'CK', name: 'Cook Islands', flagEmoji: '🇨🇰' },
  { code: 'CR', name: 'Costa Rica', flagEmoji: '🇨🇷' },
  { code: 'CI', name: "Côte d'Ivoire", flagEmoji: '🇨🇮' },
  { code: 'HR', name: 'Croatia', flagEmoji: '🇭🇷' },
  { code: 'CU', name: 'Cuba', flagEmoji: '🇨🇺' },
  { code: 'CW', name: 'Curaçao', flagEmoji: '🇨🇼' },
  { code: 'CY', name: 'Cyprus', flagEmoji: '🇨🇾' },
  { code: 'CZ', name: 'Czechia', flagEmoji: '🇨🇿' },
  { code: 'DK', name: 'Denmark', flagEmoji: '🇩🇰' },
  { code: 'DJ', name: 'Djibouti', flagEmoji: '🇩🇯' },
  { code: 'DM', name: 'Dominica', flagEmoji: '🇩🇲' },
  { code: 'DO', name: 'Dominican Republic', flagEmoji: '🇩🇴' },
  { code: 'EC', name: 'Ecuador', flagEmoji: '🇪🇨' },
  { code: 'EG', name: 'Egypt', flagEmoji: '🇪🇬' },
  { code: 'SV', name: 'El Salvador', flagEmoji: '🇸🇻' },
  { code: 'GQ', name: 'Equatorial Guinea', flagEmoji: '🇬🇶' },
  { code: 'ER', name: 'Eritrea', flagEmoji: '🇪🇷' },
  { code: 'EE', name: 'Estonia', flagEmoji: '🇪🇪' },
  { code: 'SZ', name: 'Eswatini', flagEmoji: '🇸🇿' },
  { code: 'ET', name: 'Ethiopia', flagEmoji: '🇪🇹' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', flagEmoji: '🇫🇰' },
  { code: 'FO', name: 'Faroe Islands', flagEmoji: '🇫🇴' },
  { code: 'FJ', name: 'Fiji', flagEmoji: '🇫🇯' },
  { code: 'FI', name: 'Finland', flagEmoji: '🇫🇮' },
  { code: 'FR', name: 'France', flagEmoji: '🇫🇷' },
  { code: 'GF', name: 'French Guiana', flagEmoji: '🇬🇫' },
  { code: 'PF', name: 'French Polynesia', flagEmoji: '🇵🇫' },
  { code: 'TF', name: 'French Southern Territories', flagEmoji: '🇹🇫' },
  { code: 'GA', name: 'Gabon', flagEmoji: '🇬🇦' },
  { code: 'GM', name: 'Gambia', flagEmoji: '🇬🇲' },
  { code: 'GE', name: 'Georgia', flagEmoji: '🇬🇪' },
  { code: 'DE', name: 'Germany', flagEmoji: '🇩🇪' },
  { code: 'GH', name: 'Ghana', flagEmoji: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', flagEmoji: '🇬🇮' },
  { code: 'GR', name: 'Greece', flagEmoji: '🇬🇷' },
  { code: 'GL', name: 'Greenland', flagEmoji: '🇬🇱' },
  { code: 'GD', name: 'Grenada', flagEmoji: '🇬🇩' },
  { code: 'GP', name: 'Guadeloupe', flagEmoji: '🇬🇵' },
  { code: 'GU', name: 'Guam', flagEmoji: '🇬🇺' },
  { code: 'GT', name: 'Guatemala', flagEmoji: '🇬🇹' },
  { code: 'GG', name: 'Guernsey', flagEmoji: '🇬🇬' },
  { code: 'GN', name: 'Guinea', flagEmoji: '🇬🇳' },
  { code: 'GW', name: 'Guinea-Bissau', flagEmoji: '🇬🇼' },
  { code: 'GY', name: 'Guyana', flagEmoji: '🇬🇾' },
  { code: 'HT', name: 'Haiti', flagEmoji: '🇭🇹' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', flagEmoji: '🇭🇲' },
  { code: 'VA', name: 'Holy See', flagEmoji: '🇻🇦' },
  { code: 'HN', name: 'Honduras', flagEmoji: '🇭🇳' },
  { code: 'HK', name: 'Hong Kong', flagEmoji: '🇭🇰' },
  { code: 'HU', name: 'Hungary', flagEmoji: '🇭🇺' },
  { code: 'IS', name: 'Iceland', flagEmoji: '🇮🇸' },
  { code: 'IN', name: 'India', flagEmoji: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', flagEmoji: '🇮🇩' },
  { code: 'IR', name: 'Iran', flagEmoji: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', flagEmoji: '🇮🇶' },
  { code: 'IE', name: 'Ireland', flagEmoji: '🇮🇪' },
  { code: 'IM', name: 'Isle of Man', flagEmoji: '🇮🇲' },
  { code: 'IL', name: 'Israel', flagEmoji: '🇮🇱' },
  { code: 'IT', name: 'Italy', flagEmoji: '🇮🇹' },
  { code: 'JM', name: 'Jamaica', flagEmoji: '🇯🇲' },
  { code: 'JP', name: 'Japan', flagEmoji: '🇯🇵' },
  { code: 'JE', name: 'Jersey', flagEmoji: '🇯🇪' },
  { code: 'JO', name: 'Jordan', flagEmoji: '🇯🇴' },
  { code: 'KZ', name: 'Kazakhstan', flagEmoji: '🇰🇿' },
  { code: 'KE', name: 'Kenya', flagEmoji: '🇰🇪' },
  { code: 'KI', name: 'Kiribati', flagEmoji: '🇰🇮' },
  { code: 'KP', name: 'Korea (Democratic People\'s Republic of)', flagEmoji: '🇰🇵' },
  { code: 'KR', name: 'Korea, Republic of', flagEmoji: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', flagEmoji: '🇰🇼' },
  { code: 'KG', name: 'Kyrgyzstan', flagEmoji: '🇰🇬' },
  { code: 'LA', name: 'Lao People\'s Democratic Republic', flagEmoji: '🇱🇦' },
  { code: 'LV', name: 'Latvia', flagEmoji: '🇱🇻' },
  { code: 'LB', name: 'Lebanon', flagEmoji: '🇱🇧' },
  { code: 'LS', name: 'Lesotho', flagEmoji: '🇱🇸' },
  { code: 'LR', name: 'Liberia', flagEmoji: '🇱🇷' },
  { code: 'LY', name: 'Libya', flagEmoji: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', flagEmoji: '🇱🇮' },
  { code: 'LT', name: 'Lithuania', flagEmoji: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', flagEmoji: '🇱🇺' },
  { code: 'MO', name: 'Macao', flagEmoji: '🇲🇴' },
  { code: 'MG', name: 'Madagascar', flagEmoji: '🇲🇬' },
  { code: 'MW', name: 'Malawi', flagEmoji: '🇲🇼' },
  { code: 'MY', name: 'Malaysia', flagEmoji: '🇲🇾' },
  { code: 'MV', name: 'Maldives', flagEmoji: '🇲🇻' },
  { code: 'ML', name: 'Mali', flagEmoji: '🇲🇱' },
  { code: 'MT', name: 'Malta', flagEmoji: '🇲🇹' },
  { code: 'MH', name: 'Marshall Islands', flagEmoji: '🇲🇭' },
  { code: 'MQ', name: 'Martinique', flagEmoji: '🇲🇶' },
  { code: 'MR', name: 'Mauritania', flagEmoji: '🇲🇷' },
  { code: 'MU', name: 'Mauritius', flagEmoji: '🇲🇺' },
  { code: 'YT', name: 'Mayotte', flagEmoji: '🇾🇹' },
  { code: 'MX', name: 'Mexico', flagEmoji: '🇲🇽' },
  { code: 'FM', name: 'Micronesia (Federated States of)', flagEmoji: '🇫🇲' },
  { code: 'MD', name: 'Moldova, Republic of', flagEmoji: '🇲🇩' },
  { code: 'MC', name: 'Monaco', flagEmoji: '🇲🇨' },
  { code: 'MN', name: 'Mongolia', flagEmoji: '🇲🇳' },
  { code: 'ME', name: 'Montenegro', flagEmoji: '🇲🇪' },
  { code: 'MS', name: 'Montserrat', flagEmoji: '🇲🇸' },
  { code: 'MA', name: 'Morocco', flagEmoji: '🇲🇦' },
  { code: 'MZ', name: 'Mozambique', flagEmoji: '🇲🇿' },
  { code: 'MM', name: 'Myanmar', flagEmoji: '🇲🇲' },
  { code: 'NA', name: 'Namibia', flagEmoji: '🇳🇦' },
  { code: 'NR', name: 'Nauru', flagEmoji: '🇳🇷' },
  { code: 'NP', name: 'Nepal', flagEmoji: '🇳🇵' },
  { code: 'NL', name: 'Netherlands', flagEmoji: '🇳🇱' },
  { code: 'NC', name: 'New Caledonia', flagEmoji: '🇳🇨' },
  { code: 'NZ', name: 'New Zealand', flagEmoji: '🇳🇿' },
  { code: 'NI', name: 'Nicaragua', flagEmoji: '🇳🇮' },
  { code: 'NE', name: 'Niger', flagEmoji: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', flagEmoji: '🇳🇬' },
  { code: 'NU', name: 'Niue', flagEmoji: '🇳🇺' },
  { code: 'NF', name: 'Norfolk Island', flagEmoji: '🇳🇫' },
  { code: 'MK', name: 'North Macedonia', flagEmoji: '🇲🇰' },
  { code: 'MP', name: 'Northern Mariana Islands', flagEmoji: '🇲🇵' },
  { code: 'NO', name: 'Norway', flagEmoji: '🇳🇴' },
  { code: 'OM', name: 'Oman', flagEmoji: '🇴🇲' },
  { code: 'PK', name: 'Pakistan', flagEmoji: '🇵🇰' },
  { code: 'PW', name: 'Palau', flagEmoji: '🇵🇼' },
  { code: 'PS', name: 'Palestine, State of', flagEmoji: '🇵🇸' },
  { code: 'PA', name: 'Panama', flagEmoji: '🇵🇦' },
  { code: 'PG', name: 'Papua New Guinea', flagEmoji: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', flagEmoji: '🇵🇾' },
  { code: 'PE', name: 'Peru', flagEmoji: '🇵🇪' },
  { code: 'PH', name: 'Philippines', flagEmoji: '🇵🇭' },
  { code: 'PN', name: 'Pitcairn', flagEmoji: '🇵🇳' },
  { code: 'PL', name: 'Poland', flagEmoji: '🇵🇱' },
  { code: 'PT', name: 'Portugal', flagEmoji: '🇵🇹' },
  { code: 'PR', name: 'Puerto Rico', flagEmoji: '🇵🇷' },
  { code: 'QA', name: 'Qatar', flagEmoji: '🇶🇦' },
  { code: 'RE', name: 'Réunion', flagEmoji: '🇷🇪' },
  { code: 'RO', name: 'Romania', flagEmoji: '🇷🇴' },
  { code: 'RU', name: 'Russian Federation', flagEmoji: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', flagEmoji: '🇷🇼' },
  { code: 'BL', name: 'Saint Barthélemy', flagEmoji: '🇧🇱' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', flagEmoji: '🇸🇭' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flagEmoji: '🇰🇳' },
  { code: 'LC', name: 'Saint Lucia', flagEmoji: '🇱🇨' },
  { code: 'MF', name: 'Saint Martin (French part)', flagEmoji: '🇲🇫' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', flagEmoji: '🇵🇲' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flagEmoji: '🇻🇨' },
  { code: 'WS', name: 'Samoa', flagEmoji: '🇼🇸' },
  { code: 'SM', name: 'San Marino', flagEmoji: '🇸🇲' },
  { code: 'ST', name: 'Sao Tome and Principe', flagEmoji: '🇸🇹' },
  { code: 'SA', name: 'Saudi Arabia', flagEmoji: '🇸🇦' },
  { code: 'SN', name: 'Senegal', flagEmoji: '🇸🇳' },
  { code: 'RS', name: 'Serbia', flagEmoji: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', flagEmoji: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', flagEmoji: '🇸🇱' },
  { code: 'SG', name: 'Singapore', flagEmoji: '🇸🇬' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', flagEmoji: '🇸🇽' },
  { code: 'SK', name: 'Slovakia', flagEmoji: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', flagEmoji: '🇸🇮' },
  { code: 'SB', name: 'Solomon Islands', flagEmoji: '🇸🇧' },
  { code: 'SO', name: 'Somalia', flagEmoji: '🇸🇴' },
  { code: 'ZA', name: 'South Africa', flagEmoji: '🇿🇦' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', flagEmoji: '🇬🇸' },
  { code: 'SS', name: 'South Sudan', flagEmoji: '🇸🇸' },
  { code: 'ES', name: 'Spain', flagEmoji: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', flagEmoji: '🇱🇰' },
  { code: 'SD', name: 'Sudan', flagEmoji: '🇸🇩' },
  { code: 'SR', name: 'Suriname', flagEmoji: '🇸🇷' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', flagEmoji: '🇸🇯' },
  { code: 'SE', name: 'Sweden', flagEmoji: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', flagEmoji: '🇨🇭' },
  { code: 'SY', name: 'Syrian Arab Republic', flagEmoji: '🇸🇾' },
  { code: 'TW', name: 'Taiwan, Province of China', flagEmoji: '🇹🇼' },
  { code: 'TJ', name: 'Tajikistan', flagEmoji: '🇹🇯' },
  { code: 'TZ', name: 'Tanzania, United Republic of', flagEmoji: '🇹🇿' },
  { code: 'TH', name: 'Thailand', flagEmoji: '🇹🇭' },
  { code: 'TL', name: 'Timor-Leste', flagEmoji: '🇹🇱' },
  { code: 'TG', name: 'Togo', flagEmoji: '🇹🇬' },
  { code: 'TK', name: 'Tokelau', flagEmoji: '🇹🇰' },
  { code: 'TO', name: 'Tonga', flagEmoji: '🇹🇴' },
  { code: 'TT', name: 'Trinidad and Tobago', flagEmoji: '🇹🇹' },
  { code: 'TN', name: 'Tunisia', flagEmoji: '🇹🇳' },
  { code: 'TR', name: 'Turkey', flagEmoji: '🇹🇷' },
  { code: 'TM', name: 'Turkmenistan', flagEmoji: '🇹🇲' },
  { code: 'TC', name: 'Turks and Caicos Islands', flagEmoji: '🇹🇨' },
  { code: 'TV', name: 'Tuvalu', flagEmoji: '🇹🇻' },
  { code: 'UG', name: 'Uganda', flagEmoji: '🇺🇬' },
  { code: 'UA', name: 'Ukraine', flagEmoji: '🇺🇦' },
  { code: 'AE', name: 'United Arab Emirates', flagEmoji: '🇦🇪' },
  { code: 'GB', name: 'United Kingdom of Great Britain and Northern Ireland', flagEmoji: '🇬🇧' },
  { code: 'US', name: 'United States of America', flagEmoji: '🇺🇸' },
  { code: 'UM', name: 'United States Minor Outlying Islands', flagEmoji: '🇺🇲' },
  { code: 'UY', name: 'Uruguay', flagEmoji: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', flagEmoji: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu', flagEmoji: '🇻🇺' },
  { code: 'VE', name: 'Venezuela', flagEmoji: '🇻🇪' },
  { code: 'VN', name: 'Viet Nam', flagEmoji: '🇻🇳' },
  { code: 'VG', name: 'Virgin Islands (British)', flagEmoji: '🇻🇬' },
  { code: 'VI', name: 'Virgin Islands (U.S.)', flagEmoji: '🇻🇮' },
  { code: 'WF', name: 'Wallis and Futuna', flagEmoji: '🇼🇫' },
  { code: 'EH', name: 'Western Sahara', flagEmoji: '🇪🇭' },
  { code: 'YE', name: 'Yemen', flagEmoji: '🇾🇪' },
  { code: 'ZM', name: 'Zambia', flagEmoji: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flagEmoji: '🇿🇼' },
];

const regions = [
  { name: 'Europe', slug: 'eu-west', description: 'European region' },
  { name: 'North America', slug: 'us-east', description: 'North American region' },
  { name: 'Asia-Pacific', slug: 'ap-south', description: 'Asia-Pacific region' },
  { name: 'US West', slug: 'us-west', description: 'US West Coast region' },
  { name: 'South America', slug: 'sa-east', description: 'South American region' },
  { name: 'Middle East', slug: 'me-south', description: 'Middle East region' },
  { name: 'Africa', slug: 'af-south', description: 'African region' },
  { name: 'Canada', slug: 'ca-central', description: 'Canadian region' },
];

async function main() {
  console.log('Seeding countries...');
  for (const country of countries) {
    await prisma.country.upsert({
      where: { code: country.code },
      update: {},
      create: country,
    });
  }
  console.log(`Seeded ${countries.length} countries.`);

  console.log('Seeding regions...');
  for (const region of regions) {
    await prisma.region.upsert({
      where: { slug: region.slug },
      update: {},
      create: region,
    });
  }
  console.log(`Seeded ${regions.length} regions.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
